name: Built tests on Linux (Gcc/Clang)

on: [push, pull_request]

jobs:
  Build-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - {cpp: g++, c: gcc}
          - {cpp: clang++, c: clang}
        build-type: [Debug, Release]
        shared-lib: [ON, OFF]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GTest
        run: |
          sudo apt install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt

      - name: Build tests
        run: |
          cmake -S . -B build -DJacLib_BUILD_TESTS=ON
          cmake --build build
        env:
          CXX: ${{ matrix.compiler.cpp }}
          CC: ${{ matrix.compiler.c }}
          CMAKE_BUILD_TYPE: ${{ matrix.build-type }}
          SHARED_LIB: ${{ matrix.shared-lib }}

      - name: Run tests
        run: |
          ./build/tst/JacLib_tests
