name: Build tests on Linux (Gcc/Clang)

on:
  pull_request:
    branches:
      - main

jobs:
  Build-Tests:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        compiler:
          - {cpp: g++, c: gcc}
          - {cpp: clang++, c: clang}
        build-type: [Debug, Release]
        shared-lib: [ON, OFF]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GTest
        run: |
          sudo apt update
          sudo apt install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt

      - name: Install Compiler
        run: |
          sudo apt install -y ${{ matrix.compiler.c }}

      - name: Build tests
        run: |
          cmake -S . -B build -DJAC_BUILD_TESTS=ON -DJacLib_BUILD_SHARED_LIBS=${SHARED_LIB} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
          cmake --build build
        env:
          CXX: ${{ matrix.compiler.cpp }}
          CC: ${{ matrix.compiler.c }}
          CMAKE_BUILD_TYPE: ${{ matrix.build-type }}
          SHARED_LIB: ${{ matrix.shared-lib }}

      - name: Run tests
        run: |
          ./build/tst/JacLib_tests
